<?php


namespace App\Services;

use App\Models\LinkModel;

/**
 * 友链管理-服务类
 * @author 牧羊人
 * @since 2020/8/28
 * Class LinkService
 * @package App\Services
 */
class LinkService extends BaseService
{
    /**
     * 构造函数
     * @author 牧羊人
     * @since 2020/8/28
     * LinkService constructor.
     */
    public function __construct()
    {
        $this->model = new LinkModel();
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2020/8/30
     * @author 牧羊人
     */
    public function edit()
    {
        // 参数
        $data = request()->all();
        // 友链形式
        $form = (int)$data['form'];
        // 图片
        $image = trim($data['image']);
        // 图片验证
        if ($form == 2) {
            // 图片
            if (!$image) {
                return message('请上传图片', false);
            }
            if (strpos($image, "temp") !== false) {
                $data['image'] = save_image($image, 'link');
            }
        } else {
            // 文字
            $data['image'] = '';
        }
        return parent::edit($data); // TODO: Change the autogenerated stub
    }
}
