<?php


namespace App\Models;

/**
 * 栏目模型
 * @author 牧羊人
 * @since 2020/11/11
 * Class ItemCateModel
 * @package App\Models
 */
class ItemCateModel extends BaseModel
{
    // 设置数据表
    protected $table = 'item_cate';

    /**
     * 获取记录信息
     * @param int $id
     * @return array|string
     * @author 牧羊人
     * @since 2020/11/11
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 封面
            if ($info['cover']) {
                $info['cover'] = get_image_url($info['cover']);
            }
        }
        return $info;
    }

    /**
     * 获取栏目名称
     * @param $cateId 栏目ID
     * @param string $delimiter 分隔符
     * @return string|null
     * @since 2020/11/11
     * @author 牧羊人
     */
    public function getCateName($cateId, $delimiter = "")
    {
        do {
            $info = $this->getInfo($cateId);
            $names[] = $info['name'];
            $cateId = $info['pid'];
        } while ($cateId > 0);
        if (!empty($names)) {
            $names = array_reverse($names);
            if (count($names) >= 2) {
                if (strpos($names[1], $names[0]) === 0) {
                    unset($names[0]);
                }
            }
            return implode($delimiter, $names);
        }
        return null;
    }

}
