<?php


namespace App\Models;

/**
 * 站点-模型
 * @author 牧羊人
 * @since 2020/11/11
 * Class ItemModel
 * @package App\Models
 */
class ItemModel extends BaseModel
{
    // 设置数据表
    protected $table = 'item';

    /**
     * 获取数据信息
     * @param int $id 记录ID
     * @return array|string
     * @author 牧羊人
     * @since 2020/11/11
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 站点图片
            if ($info['image']) {
                $info['image'] = get_image_url($info['image']);
            }
        }
        return $info;
    }

}
