<?php


namespace App\Models;

/**
 * 布局描述-模型
 * @author 牧羊人
 * @since 2020/11/11
 * Class LayoutDescModel
 * @package App\Models
 */
class LayoutDescModel extends BaseModel
{
    // 设置数据表
    protected $table = 'layout_desc';

    /**
     * 获取数据信息
     * @param int $id
     * @return array|string
     * @author 牧羊人
     * @since 2020/11/11
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 站点名称
            if ($info['item_id']) {
                $itemModel = new ItemModel();
                $itemInfo = $itemModel->getInfo($info['item_id']);
                if ($itemInfo) {
                    $info['item_name'] = $itemInfo['name'];
                }
            }
        }
        return $info;
    }

}
