<?php


namespace App\Models;

use App\Services\UserRoleService;

/**
 * 人员管理-模型
 * @author 牧羊人
 * @since 2020/11/10
 * Class AdminModel
 * @package App\Models
 */
class UserModel extends BaseModel
{
    // 设置数据表
    protected $table = 'user';

    /**
     * 获取数据信息
     * @param int $id 用户ID
     * @return array|string
     * @author 牧羊人
     * @since 2020/11/10
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 头像
            if ($info['avatar']) {
                $info['avatar'] = get_image_url($info['avatar']);
            }

            // 性别
            if ($info['gender']) {
                $info['gender_name'] = config('admin.gender_list')[$info['gender']];
            }

            // 岗位
            if ($info['position_id']) {
                $positionModel = new PositionModel();
                $positionInfo = $positionModel->getInfo($info['position_id']);
                $info['position_name'] = $positionInfo['name'];
            }

            // 职级
            if ($info['level_id']) {
                $levelMod = new LevelModel();
                $levelInfo = $levelMod->getInfo($info['level_id']);
                $info['level_name'] = $levelInfo['name'];
            }
            // 获取用户角色列表
            $userRoleService = new UserRoleService();
            $roleList = $userRoleService->getUserRoleList($id);
            $info['roles'] = $roleList;
        }
        return $info;
    }
}
