<?php


namespace App\Services;

use App\Models\LinkModel;

/**
 * 友链管理-服务类
 * @author 牧羊人
 * @since 2020/11/11
 * Class LinkService
 * @package App\Services
 */
class LinkService extends BaseService
{
    /**
     * 构造函数
     * @author 牧羊人
     * @since 2020/11/11
     * LinkService constructor.
     */
    public function __construct()
    {
        $this->model = new LinkModel();
    }

    /**
     * 获取友链列表
     * @return array
     * @since 2020/11/11
     * @author 牧羊人
     */
    public function getList()
    {
        $param = request()->all();

        // 查询条件
        $map = [];

        // 友链平台
        $platform = getter($param, "platform");
        if ($platform) {
            $map[] = ["platform", '=', $platform];
        }
        return parent::getList($map); // TODO: Change the autogenerated stub
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2020/11/11
     * @author 牧羊人
     */
    public function edit()
    {
        $data = request()->all();

        // 图片处理
        $image = trim($data['image']);
        if (!$data['id'] && !$image) {
            return message('请上传友链图片', false);
        }
        if (strpos($image, "temp")) {
            $data['image'] = save_image($image, 'item');
        } else {
            $data['image'] = str_replace(IMG_URL, "", $data['image']);
        }
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

}
