<?php


namespace App\Models;

/**
 * 友链管理-模型
 * @author 牧羊人
 * @since 2020/8/28
 * Class LinkModel
 * @package App\Models
 */
class LinkModel extends BaseModel
{
    // 设置数据表
    protected $table = "link";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return array|string
     * @author 牧羊人
     * @since 2020/8/29
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 友链图片
            if ($info['image']) {
                $info['image_url'] = get_image_url($info['image']);
            }

            // 使用平台
            if ($info['platform']) {
                $info['platform_name'] = config('admin.link_platform')[$info['platform']];
            }

            // 友链形式
            if ($info['form']) {
                $info['form_name'] = config('admin.link_form')[$info['form']];
            }

            // 友链类型
            if ($info['type']) {
                $info['type_name'] = config('admin.link_type')[$info['type']];
            }
        }
        return $info;
    }
}
