<?php
// +----------------------------------------------------------------------
// | RXThinkCMF框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2020 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | Author: 牧羊人 <1175401194@qq.com>
// +----------------------------------------------------------------------

namespace App\Models;

/**
 * 演示-模型

 * @author 牧羊人
 * @since 2020/09/01
 * Class DemoModel
 * @package App\Models
 */
class DemoModel extends BaseModel
{
    // 设置数据表
    protected $table = "demo";

    /**
     * 获取记录信息
     * @param int $id 记录ID
     * @author 牧羊人
     * @since: 2020/09/01
     */
    /**
     *
     * @param int $id
     * @return array|string
     * @author 牧羊人
     * @since 2020/9/1
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {

            // 头像
            $info['avatar'] = get_image_url($info['avatar']);

        }
        return $info;
    }
}
